# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5gVc-xXsU7vL2-QY4Z26j-Z23YSIyhI

# Armazém

## Seção de Frutas
"""

# Custo das frutas em KG
banana = 1.99
maca = 3.45
laranja = 1.49
limao = 1.19
frutas1 = ['banana', 'maçã', 'laranja', 'limão']
frutas2 = [banana, maca, laranja, limao]
frutas = dict(zip(frutas1, frutas2))

# Preço de venda das frutas em KG
banana1 = 3.99
maca1 = 8.99
laranja1 = 5.99
limao1 = 6.99

# Lista de preço de venda das frutas
vendas_frutas1 = [banana1, maca1, laranja1, limao1]

# Venda de bananas e maçãs
banana2 = float(input('Digite a quantidade de bananas vendidas: '))
maca2 = float(input('Digite a quantidade de maçãs vendidas: '))
laranja2 = float(input('Digite a quantidade de laranjas vendidas: '))
limao2 = float(input('Digite a quantidade de limões vendidos: '))

# Total de bananas, maçãs, laranjas e limões vendidos
print('O total de bananas vendidas foi de: R$', banana2 * banana1)
print('O total de maçãs vendidas foi de: R$', maca2 * maca1)
print('O total de laranjas vendidas foi de: R$', laranja2 * laranja1)
print('O total de limões vendidos foi de: R$', limao2 * limao1)

# Lista de frutas
for val in frutas1:
    print(val)

# Custo das Frutas
for val in frutas2:
    print(val)

# Preço das Frutas
for val in vendas_frutas1:
    print(val)

# Soma das vendas
soma_banana = banana2 * banana1
soma_maca = maca2 * maca1
soma_laranja = laranja2 * laranja1
soma_limao = limao2 * limao1
vendas1 = [soma_banana, soma_maca, soma_laranja, soma_limao]
total1 = sum(vendas1)
print('O total de vendas foi de: R$', total1)

# Média das vendas
media1 = total1 / 4
print('A média das vendas foi de: R$', media1)
